require("xexperimente.plugins.colors")
require("xexperimente.plugins.snacks")
require("xexperimente.plugins.treesitter")
require("xexperimente.plugins.blink")
require("xexperimente.plugins.tiny_diag")
